refactor: move Homebrew init to homebrew.zsh
Move the Homebrew initialization logic from `.zprofile` to `homebrew.zsh` to avoid redundant initializations and streamline the shell environment setup. This ensures Homebrew is initialized only once.

diff --git a/homedir/dot_zsh/executable_homebrew.zsh.tmpl b/homedir/dot_zsh/executable_homebrew.zsh.tmpl
--- a/homedir/dot_zsh/executable_homebrew.zsh.tmpl
+++ b/homedir/dot_zsh/executable_homebrew.zsh.tmpl
@@ -1,3 +1,11 @@
+{{- if eq .chezmoi.os "darwin" -}}
+eval "$(/opt/homebrew/bin/brew shellenv)"
+{{- else if eq .chezmoi.os "linux" -}}
+eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+{{ else }}
+echo "Error: Homebrew not supported on OS: {{ .chezmoi.os }} Arch: {{ .chezmoi.arch }}" && exit 1
+{{ end }}
+
 # Homebrew environment setup
 if (( $+commands[brew] )); then
   BREW_PREFIX=$(brew --prefix)
